## Preprocessing

In [2]:
pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.7.0-cp38-cp38-win_amd64.whl (430.8 MB)
Collecting flatbuffers<3.0,>=1.12
  Downloading flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
Collecting keras<2.8,>=2.7.0rc0
  Downloading keras-2.7.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\conda\lib\site-packages (from tensorflow) (3.7.4.3)
Collecting termcolor>=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting opt-einsum>=2.3.2
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting protobuf>=3.9.2
  Downloading protobuf-3.19.1-cp38-cp38-win_amd64.whl (895 kB)
Requirement already satisfied: six>=1.12.0 in c:\conda\lib\site-packages (from tensorflow) (1.15.0)
Collecting absl-py>=0.4.0
  Downloading absl_py-1.0.0-py3-none-any.whl (126 kB)
Collecting libclang>=9.0.1
  Downloading libclang-12.0.0-py2.py3-none-win_amd64.whl (13.1 MB)
Collecting keras-preprocessing>=1.1.1
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting tensorflow-estimator<2.8,~=2.7.0rc0
  Downloading tensorflow_estimator-2.7.0-py2.py3-none-any.whl (463 kB)
Requirement already satisfied: numpy>=1.14.5 in c:\conda\lib\site-packages (from tensorflow) (1.20.1)
Requirement already satisfied: wrapt>=1.11.0 in c:\conda\lib\site-packages (from tensorflow) (1.12.1)
Collecting gast<0.5.0,>=0.2.1
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Requirement already satisfied: h5py>=2.9.0 in c:\conda\lib\site-packages (from tensorflow) (2.10.0)
Collecting grpcio<2.0,>=1.24.3
  Downloading grpcio-1.41.1-cp38-cp38-win_amd64.whl (3.2 MB)
Collecting tensorboard~=2.6
  Downloading tensorboard-2.7.0-py3-none-any.whl (5.8 MB)
Collecting tensorflow-io-gcs-filesystem>=0.21.0
  Downloading tensorflow_io_gcs_filesystem-0.22.0-cp38-cp38-win_amd64.whl (1.5 MB)
Collecting google-pasta>=0.1.1
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting astunparse>=1.6.0
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: wheel<1.0,>=0.32.0 in c:\conda\lib\site-packages (from tensorflow) (0.36.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\conda\lib\site-packages (from tensorboard~=2.6->tensorflow) (2.25.1)
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.5-py3-none-any.whl (97 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: werkzeug>=0.11.15 in c:\conda\lib\site-packages (from tensorboard~=2.6->tensorflow) (1.0.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\conda\lib\site-packages (from tensorboard~=2.6->tensorflow) (52.0.0.post20210125)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.3.3-py2.py3-none-any.whl (155 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
Collecting cachetools<5.0,>=2.0.0
  Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\conda\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (4.7.2)
Collecting requests-oauthlib>=0.7.0
Note: you may need to restart the kernel to use updated packages.
  Downloading requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: importlib-metadata>='4.4' in c:\conda\lib\site-packages (from markdown>=2.6.8->tensorboard~=2.6->tensorflow) (3.10.0)
Requirement already satisfied: zipp>=0.5 in c:\conda\lib\site-packages (from importlib-metadata>='4.4'->markdown>=2.6.8->tensorboard~=2.6->tensorflow) (3.4.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\conda\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\conda\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in c:\conda\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\conda\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\conda\lib\site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow) (4.0.0)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.1.1-py2.py3-none-any.whl (146 kB)
Building wheels for collected packages: termcolor
  Building wheel for termcolor (setup.py): started
  Building wheel for termcolor (setup.py): finished with status 'done'
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4829 sha256=35c93d904e79d34595e5e428792aac86e0d435c1ec379210ded2e8a3db6674d3
  Stored in directory: c:\users\sean & lauren\appdata\local\pip\cache\wheels\a0\16\9c\5473df82468f958445479c59e784896fa24f4a5fc024b0f501
Successfully built termcolor
Installing collected packages: pyasn1-modules, oauthlib, cachetools, requests-oauthlib, google-auth, tensorboard-plugin-wit, tensorboard-data-server, protobuf, markdown, grpcio, google-auth-oauthlib, absl-py, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard, opt-einsum, libclang, keras-preprocessing, keras, google-pasta, gast, flatbuffers, astunparse, tensorflow
Successfully installed absl-py-1.0.0 astunparse-1.6.3 cachetools-4.2.4 flatbuffers-2.0 gast-0.4.0 google-auth-2.3.3 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.41.1 keras-2.7.0 keras-preprocessing-1.1.2 libclang-12.0.0 markdown-3.3.5 oauthlib-3.1.1 opt-einsum-3.3.0 protobuf-3.19.1 pyasn1-modules-0.2.8 requests-oauthlib-1.3.0 tensorboard-2.7.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorflow-2.7.0 tensorflow-estimator-2.7.0 tensorflow-io-gcs-filesystem-0.22.0 termcolor-1.1.0

In [75]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("../Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [76]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'

application_df = application_df.drop(['EIN','NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [124]:
application_df.nunique()

APPLICATION_TYPE             9
AFFILIATION                  6
CLASSIFICATION               6
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [78]:
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [79]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#cuttoff is 300
application_types_to_replace = ['T17','T29','T15','T25','T14','T2','T12','T13','T9']


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [80]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C1580        1
C2380        1
C2600        1
C4200        1
C1728        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [81]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1237        9
C1235        9
C7210        7
C1720        6
C4100        6
C2400        6
C1257        5
C1600        5
C2710        3
C1260        3
C0           3
C1256        2
C1234        2
C1246        2
C3200        2
C1267        2
Name: CLASSIFICATION, dtype: int64

In [82]:
application_df['CLASSIFICATION'].unique()

array(['C1000', 'C2000', 'C3000', 'C1200', 'C2700', 'C7000', 'C7200',
       'C1700', 'C4000', 'C7100', 'C2800', 'C6000', 'C2100', 'C1238',
       'C5000', 'C7120', 'C1800', 'C4100', 'C1400', 'C1270', 'C2300',
       'C8200', 'C1500', 'C7210', 'C1300', 'C1230', 'C1280', 'C1240',
       'C2710', 'C2561', 'C1250', 'C8000', 'C1245', 'C1260', 'C1235',
       'C1720', 'C1257', 'C4500', 'C2400', 'C8210', 'C1600', 'C1278',
       'C1237', 'C4120', 'C2170', 'C1728', 'C1732', 'C2380', 'C1283',
       'C1570', 'C2500', 'C1267', 'C3700', 'C1580', 'C2570', 'C1256',
       'C1236', 'C1234', 'C1246', 'C2190', 'C4200', 'C0', 'C3200',
       'C5200', 'C1370', 'C2600', 'C1248', 'C6100', 'C1820', 'C1900',
       'C2150'], dtype=object)

In [83]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#cutoff is 1000
classifications_to_replace= ['C2700', 'C7000', 'C7200',
       'C1700', 'C4000', 'C7100', 'C2800', 'C6000', 'C1238',
       'C5000', 'C7120', 'C1800', 'C4100', 'C1400', 'C1270', 'C2300',
       'C8200', 'C1500', 'C7210', 'C1300', 'C1230', 'C1280', 'C1240',
       'C2710', 'C2561', 'C1250', 'C8000', 'C1245', 'C1260', 'C1235',
       'C1720', 'C1257', 'C4500', 'C2400', 'C8210', 'C1600', 'C1278',
       'C1237', 'C4120', 'C2170', 'C1728', 'C1732', 'C2380', 'C1283',
       'C1570', 'C2500', 'C1267', 'C3700', 'C1580', 'C2570', 'C1256',
       'C1236', 'C1234', 'C1246', 'C2190', 'C4200', 'C0', 'C3200',
       'C5200', 'C1370', 'C2600', 'C1248', 'C6100', 'C1820', 'C1900',
       'C2150']

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [84]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies = pd.get_dummies(application_df)
print(dummies.columns)
dummies

Index(['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL', 'APPLICATION_TYPE_Other',
       'APPLICATION_TYPE_T10', 'APPLICATION_TYPE_T19', 'APPLICATION_TYPE_T3',
       'APPLICATION_TYPE_T4', 'APPLICATION_TYPE_T5', 'APPLICATION_TYPE_T6',
       'APPLICATION_TYPE_T7', 'APPLICATION_TYPE_T8',
       'AFFILIATION_CompanySponsored', 'AFFILIATION_Family/Parent',
       'AFFILIATION_Independent', 'AFFILIATION_National', 'AFFILIATION_Other',
       'AFFILIATION_Regional', 'CLASSIFICATION_C1000', 'CLASSIFICATION_C1200',
       'CLASSIFICATION_C2000', 'CLASSIFICATION_C2100', 'CLASSIFICATION_C3000',
       'CLASSIFICATION_Other', 'USE_CASE_CommunityServ', 'USE_CASE_Heathcare',
       'USE_CASE_Other', 'USE_CASE_Preservation', 'USE_CASE_ProductDev',
       'ORGANIZATION_Association', 'ORGANIZATION_Co-operative',
       'ORGANIZATION_Corporation', 'ORGANIZATION_Trust', 'INCOME_AMT_0',
       'INCOME_AMT_1-9999', 'INCOME_AMT_10000-24999',
       'INCOME_AMT_100000-499999', 'INCOME_AMT_10M-50M', 'INCOME_AMT_1M-5M',
       'INCOME_AMT_25000-99999', 'INCOME_AMT_50M+', 'INCOME_AMT_5M-10M',
       'SPECIAL_CONSIDERATIONS_N', 'SPECIAL_CONSIDERATIONS_Y'],
      dtype='object')

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [85]:
# Split our preprocessed data into our features and target arrays
X_dummies = dummies.drop('IS_SUCCESSFUL', axis=1)
y=dummies['IS_SUCCESSFUL']


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X_dummies, y, random_state=1)

In [86]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

#### Test 1

In [118]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=8, activation="relu", input_dim=43))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=6, activation="relu", input_dim=43))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=3, activation='tanh', input_dim=43))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=8, activation='tanh', input_dim=43))

# Fifth hidden layer
nn.add(tf.keras.layers.Dense(units=5, activation="sigmoid", input_dim=43))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_34 (Dense)            (None, 8)                 352

 dense_35 (Dense)            (None, 6)                 54

 dense_36 (Dense)            (None, 3)                 21

 dense_37 (Dense)            (None, 8)                 32

 dense_38 (Dense)            (None, 5)                 45

 dense_39 (Dense)            (None, 1)                 6

=================================================================
Total params: 510
Trainable params: 510
Non-trainable params: 0
_________________________________________________________________
Epoch 1/50
804/804 [==============================] - 1s 956us/step - loss: 0.6131 - accuracy: 0.6788
Epoch 2/50
804/804 [==============================] - 1s 708us/step - loss: 0.5650 - accuracy: 0.7282
Epoch 3/50
804/804 [==============================] - 1s 772us/step - loss: 0.5610 - accuracy: 0.7298
Epoch 4/50
804/804 [==============================] - 1s 644us/step - loss: 0.5585 - accuracy: 0.7296
Epoch 5/50
804/804 [==============================] - 0s 587us/step - loss: 0.5572 - accuracy: 0.7290
Epoch 6/50
804/804 [==============================] - 0s 571us/step - loss: 0.5565 - accuracy: 0.7290
Epoch 7/50
804/804 [==============================] - 0s 569us/step - loss: 0.5557 - accuracy: 0.7297
Epoch 8/50
804/804 [==============================] - 0s 568us/step - loss: 0.5553 - accuracy: 0.7293
Epoch 9/50
804/804 [==============================] - 0s 568us/step - loss: 0.5545 - accuracy: 0.7305
Epoch 10/50
804/804 [==============================] - 1s 702us/step - loss: 0.5541 - accuracy: 0.7308
Epoch 11/50
804/804 [==============================] - 0s 572us/step - loss: 0.5532 - accuracy: 0.7299
Epoch 12/50
804/804 [==============================] - 1s 646us/step - loss: 0.5532 - accuracy: 0.7312
Epoch 13/50
804/804 [==============================] - 0s 595us/step - loss: 0.5525 - accuracy: 0.7315
Epoch 14/50
804/804 [==============================] - 1s 624us/step - loss: 0.5521 - accuracy: 0.7319
Epoch 15/50
804/804 [==============================] - 0s 585us/step - loss: 0.5517 - accuracy: 0.7306
Epoch 16/50
804/804 [==============================] - 0s 575us/step - loss: 0.5513 - accuracy: 0.7326
Epoch 17/50
804/804 [==============================] - 0s 560us/step - loss: 0.5508 - accuracy: 0.7323
Epoch 18/50
804/804 [==============================] - 0s 573us/step - loss: 0.5503 - accuracy: 0.7325
Epoch 19/50
804/804 [==============================] - 0s 564us/step - loss: 0.5498 - accuracy: 0.7322
Epoch 20/50
804/804 [==============================] - 0s 579us/step - loss: 0.5496 - accuracy: 0.7315
Epoch 21/50
804/804 [==============================] - 0s 579us/step - loss: 0.5497 - accuracy: 0.7324
Epoch 22/50
804/804 [==============================] - 0s 586us/step - loss: 0.5493 - accuracy: 0.7329
Epoch 23/50
804/804 [==============================] - 0s 596us/step - loss: 0.5492 - accuracy: 0.7331
Epoch 24/50
804/804 [==============================] - 0s 603us/step - loss: 0.5490 - accuracy: 0.7320
Epoch 25/50
804/804 [==============================] - 0s 572us/step - loss: 0.5486 - accuracy: 0.7330
Epoch 26/50
804/804 [==============================] - 0s 566us/step - loss: 0.5488 - accuracy: 0.7333
Epoch 27/50
804/804 [==============================] - 0s 587us/step - loss: 0.5485 - accuracy: 0.7330
Epoch 28/50
804/804 [==============================] - 0s 575us/step - loss: 0.5486 - accuracy: 0.7323
Epoch 29/50
804/804 [==============================] - 0s 571us/step - loss: 0.5481 - accuracy: 0.7329
Epoch 30/50
804/804 [==============================] - 0s 574us/step - loss: 0.5481 - accuracy: 0.7323
Epoch 31/50
804/804 [==============================] - 0s 563us/step - loss: 0.5479 - accuracy: 0.7329
Epoch 32/50
804/804 [==============================] - 0s 562us/step - loss: 0.5470 - accuracy: 0.7334
Epoch 33/50
804/804 [==============================] - 0s 577us/step - loss: 0.5477 - accuracy: 0.7325
Epoch 34/50
804/804 [==============================] - 0s 559us/step - loss: 0.5478 - accuracy: 0.7327
Epoch 35/50
804/804 [==============================] - 0s 588us/step - loss: 0.5474 - accuracy: 0.7343
Epoch 36/50
804/804 [==============================] - 0s 576us/step - loss: 0.5475 - accuracy: 0.7335
Epoch 37/50
804/804 [==============================] - 0s 571us/step - loss: 0.5471 - accuracy: 0.7334
Epoch 38/50
804/804 [==============================] - 0s 576us/step - loss: 0.5472 - accuracy: 0.7341
Epoch 39/50
804/804 [==============================] - 0s 561us/step - loss: 0.5467 - accuracy: 0.7341
Epoch 40/50
804/804 [==============================] - 0s 579us/step - loss: 0.5468 - accuracy: 0.7317
Epoch 41/50
804/804 [==============================] - 0s 568us/step - loss: 0.5473 - accuracy: 0.7332
Epoch 42/50
804/804 [==============================] - 0s 580us/step - loss: 0.5469 - accuracy: 0.7351
Epoch 43/50
804/804 [==============================] - 0s 567us/step - loss: 0.5468 - accuracy: 0.7334
Epoch 44/50
804/804 [==============================] - 0s 567us/step - loss: 0.5466 - accuracy: 0.7332
Epoch 45/50
804/804 [==============================] - 0s 584us/step - loss: 0.5465 - accuracy: 0.7343
Epoch 46/50
804/804 [==============================] - 0s 571us/step - loss: 0.5465 - accuracy: 0.7336
Epoch 47/50
804/804 [==============================] - 0s 583us/step - loss: 0.5465 - accuracy: 0.7344
Epoch 48/50
804/804 [==============================] - 0s 576us/step - loss: 0.5467 - accuracy: 0.7332
Epoch 49/50
804/804 [==============================] - 0s 580us/step - loss: 0.5466 - accuracy: 0.7344
Epoch 50/50
804/804 [==============================] - 0s 595us/step - loss: 0.5460 - accuracy: 0.7331
268/268 - 0s - loss: 0.5558 - accuracy: 0.7282 - 167ms/epoch - 623us/step
Loss: 0.5557711720466614, Accuracy: 0.7281632423400879

#### Test 2

In [119]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=8, activation="relu", input_dim=43))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=1, activation="relu", input_dim=43))



# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_40 (Dense)            (None, 8)                 352

 dense_41 (Dense)            (None, 1)                 9

 dense_42 (Dense)            (None, 1)                 2

=================================================================
Total params: 363
Trainable params: 363
Non-trainable params: 0
_________________________________________________________________
Epoch 1/50
804/804 [==============================] - 1s 498us/step - loss: 0.6813 - accuracy: 0.6530
Epoch 2/50
804/804 [==============================] - 0s 510us/step - loss: 0.5896 - accuracy: 0.7184
Epoch 3/50
804/804 [==============================] - 0s 512us/step - loss: 0.5776 - accuracy: 0.7211
Epoch 4/50
804/804 [==============================] - 0s 508us/step - loss: 0.5740 - accuracy: 0.7220
Epoch 5/50
804/804 [==============================] - 0s 520us/step - loss: 0.5709 - accuracy: 0.7245
Epoch 6/50
804/804 [==============================] - 0s 503us/step - loss: 0.5668 - accuracy: 0.7276
Epoch 7/50
804/804 [==============================] - 0s 507us/step - loss: 0.5653 - accuracy: 0.7279
Epoch 8/50
804/804 [==============================] - 0s 515us/step - loss: 0.5647 - accuracy: 0.7285
Epoch 9/50
804/804 [==============================] - 0s 506us/step - loss: 0.5643 - accuracy: 0.7290
Epoch 10/50
804/804 [==============================] - 0s 511us/step - loss: 0.5640 - accuracy: 0.7298
Epoch 11/50
804/804 [==============================] - 0s 513us/step - loss: 0.5632 - accuracy: 0.7308
Epoch 12/50
804/804 [==============================] - 0s 527us/step - loss: 0.5626 - accuracy: 0.7311
Epoch 13/50
804/804 [==============================] - 0s 523us/step - loss: 0.5622 - accuracy: 0.7321
Epoch 14/50
804/804 [==============================] - 0s 511us/step - loss: 0.5616 - accuracy: 0.7316
Epoch 15/50
804/804 [==============================] - 0s 512us/step - loss: 0.5615 - accuracy: 0.7320
Epoch 16/50
804/804 [==============================] - 0s 519us/step - loss: 0.5610 - accuracy: 0.7324
Epoch 17/50
804/804 [==============================] - 0s 502us/step - loss: 0.5611 - accuracy: 0.7318
Epoch 18/50
804/804 [==============================] - 0s 525us/step - loss: 0.5609 - accuracy: 0.7317
Epoch 19/50
804/804 [==============================] - 0s 617us/step - loss: 0.5602 - accuracy: 0.7322
Epoch 20/50
804/804 [==============================] - 0s 541us/step - loss: 0.5598 - accuracy: 0.7322
Epoch 21/50
804/804 [==============================] - 0s 518us/step - loss: 0.5595 - accuracy: 0.7325
Epoch 22/50
804/804 [==============================] - 0s 519us/step - loss: 0.5593 - accuracy: 0.7322
Epoch 23/50
804/804 [==============================] - 0s 505us/step - loss: 0.5589 - accuracy: 0.7323
Epoch 24/50
804/804 [==============================] - 0s 511us/step - loss: 0.5589 - accuracy: 0.7331
Epoch 25/50
804/804 [==============================] - 0s 514us/step - loss: 0.5584 - accuracy: 0.7331
Epoch 26/50
804/804 [==============================] - 0s 508us/step - loss: 0.5586 - accuracy: 0.7326
Epoch 27/50
804/804 [==============================] - 0s 526us/step - loss: 0.5581 - accuracy: 0.7328
Epoch 28/50
804/804 [==============================] - 0s 518us/step - loss: 0.5581 - accuracy: 0.7328
Epoch 29/50
804/804 [==============================] - 0s 514us/step - loss: 0.5581 - accuracy: 0.7329
Epoch 30/50
804/804 [==============================] - 0s 518us/step - loss: 0.5583 - accuracy: 0.7330
Epoch 31/50
804/804 [==============================] - 0s 515us/step - loss: 0.5582 - accuracy: 0.7324
Epoch 32/50
804/804 [==============================] - 0s 508us/step - loss: 0.5578 - accuracy: 0.7335
Epoch 33/50
804/804 [==============================] - 0s 512us/step - loss: 0.5578 - accuracy: 0.7335
Epoch 34/50
804/804 [==============================] - 0s 519us/step - loss: 0.5577 - accuracy: 0.7322
Epoch 35/50
804/804 [==============================] - 0s 524us/step - loss: 0.5577 - accuracy: 0.7328
Epoch 36/50
804/804 [==============================] - 0s 507us/step - loss: 0.5574 - accuracy: 0.7325
Epoch 37/50
804/804 [==============================] - 0s 514us/step - loss: 0.5576 - accuracy: 0.7335
Epoch 38/50
804/804 [==============================] - 0s 523us/step - loss: 0.5574 - accuracy: 0.7331
Epoch 39/50
804/804 [==============================] - 0s 513us/step - loss: 0.5574 - accuracy: 0.7332
Epoch 40/50
804/804 [==============================] - 0s 508us/step - loss: 0.5571 - accuracy: 0.7328
Epoch 41/50
804/804 [==============================] - 0s 518us/step - loss: 0.5572 - accuracy: 0.7337
Epoch 42/50
804/804 [==============================] - 0s 508us/step - loss: 0.5572 - accuracy: 0.7332
Epoch 43/50
804/804 [==============================] - 0s 507us/step - loss: 0.5570 - accuracy: 0.7334
Epoch 44/50
804/804 [==============================] - 0s 514us/step - loss: 0.5569 - accuracy: 0.7336
Epoch 45/50
804/804 [==============================] - 0s 506us/step - loss: 0.5568 - accuracy: 0.7329
Epoch 46/50
804/804 [==============================] - 0s 514us/step - loss: 0.5570 - accuracy: 0.7333
Epoch 47/50
804/804 [==============================] - 0s 509us/step - loss: 0.5570 - accuracy: 0.7327
Epoch 48/50
804/804 [==============================] - 0s 518us/step - loss: 0.5564 - accuracy: 0.7333
Epoch 49/50
804/804 [==============================] - 0s 527us/step - loss: 0.5569 - accuracy: 0.7330
Epoch 50/50
804/804 [==============================] - 0s 524us/step - loss: 0.5567 - accuracy: 0.7329
268/268 - 0s - loss: 0.5610 - accuracy: 0.7277 - 147ms/epoch - 549us/step
Loss: 0.5609530806541443, Accuracy: 0.7276967763900757

#### Test 3

In [120]:
nn = tf.keras.models.Sequential()

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=3, activation='tanh', input_dim=43))

# Fourth hidden layer
nn.add(tf.keras.layers.Dense(units=8, activation='tanh', input_dim=43))

# Fifth hidden layer
nn.add(tf.keras.layers.Dense(units=5, activation="sigmoid", input_dim=43))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_43 (Dense)            (None, 3)                 132

 dense_44 (Dense)            (None, 8)                 32

 dense_45 (Dense)            (None, 5)                 45

 dense_46 (Dense)            (None, 1)                 6

=================================================================
Total params: 215
Trainable params: 215
Non-trainable params: 0
_________________________________________________________________
Epoch 1/50
804/804 [==============================] - 1s 656us/step - loss: 0.6128 - accuracy: 0.6882
Epoch 2/50
804/804 [==============================] - 1s 704us/step - loss: 0.5711 - accuracy: 0.7278
Epoch 3/50
804/804 [==============================] - 0s 574us/step - loss: 0.5662 - accuracy: 0.7283
Epoch 4/50
804/804 [==============================] - 0s 594us/step - loss: 0.5632 - accuracy: 0.7279
Epoch 5/50
804/804 [==============================] - 0s 546us/step - loss: 0.5608 - accuracy: 0.7284
Epoch 6/50
804/804 [==============================] - 1s 654us/step - loss: 0.5593 - accuracy: 0.7295
Epoch 7/50
804/804 [==============================] - 0s 606us/step - loss: 0.5584 - accuracy: 0.7291
Epoch 8/50
804/804 [==============================] - 0s 610us/step - loss: 0.5575 - accuracy: 0.7291
Epoch 9/50
804/804 [==============================] - 0s 561us/step - loss: 0.5569 - accuracy: 0.7304
Epoch 10/50
804/804 [==============================] - 0s 553us/step - loss: 0.5564 - accuracy: 0.7297
Epoch 11/50
804/804 [==============================] - 0s 549us/step - loss: 0.5560 - accuracy: 0.7296
Epoch 12/50
804/804 [==============================] - 0s 553us/step - loss: 0.5556 - accuracy: 0.7287
Epoch 13/50
804/804 [==============================] - 0s 584us/step - loss: 0.5550 - accuracy: 0.7279
Epoch 14/50
804/804 [==============================] - 0s 564us/step - loss: 0.5548 - accuracy: 0.7302
Epoch 15/50
804/804 [==============================] - 0s 549us/step - loss: 0.5547 - accuracy: 0.7287
Epoch 16/50
804/804 [==============================] - 0s 569us/step - loss: 0.5541 - accuracy: 0.7289
Epoch 17/50
804/804 [==============================] - 0s 553us/step - loss: 0.5541 - accuracy: 0.7288
Epoch 18/50
804/804 [==============================] - 0s 542us/step - loss: 0.5537 - accuracy: 0.7281
Epoch 19/50
804/804 [==============================] - 0s 596us/step - loss: 0.5539 - accuracy: 0.7288
Epoch 20/50
804/804 [==============================] - 0s 584us/step - loss: 0.5538 - accuracy: 0.7290
Epoch 21/50
804/804 [==============================] - 0s 546us/step - loss: 0.5538 - accuracy: 0.7300
Epoch 22/50
804/804 [==============================] - 0s 556us/step - loss: 0.5536 - accuracy: 0.7297
Epoch 23/50
804/804 [==============================] - 0s 523us/step - loss: 0.5533 - accuracy: 0.7288
Epoch 24/50
804/804 [==============================] - 0s 528us/step - loss: 0.5534 - accuracy: 0.7287
Epoch 25/50
804/804 [==============================] - 0s 532us/step - loss: 0.5533 - accuracy: 0.7290
Epoch 26/50
804/804 [==============================] - 0s 538us/step - loss: 0.5532 - accuracy: 0.7286
Epoch 27/50
804/804 [==============================] - 0s 542us/step - loss: 0.5531 - accuracy: 0.7292
Epoch 28/50
804/804 [==============================] - 0s 528us/step - loss: 0.5533 - accuracy: 0.7287
Epoch 29/50
804/804 [==============================] - 0s 532us/step - loss: 0.5528 - accuracy: 0.7292
Epoch 30/50
804/804 [==============================] - 0s 543us/step - loss: 0.5529 - accuracy: 0.7285
Epoch 31/50
804/804 [==============================] - 0s 556us/step - loss: 0.5529 - accuracy: 0.7296
Epoch 32/50
804/804 [==============================] - 0s 546us/step - loss: 0.5529 - accuracy: 0.7288
Epoch 33/50
804/804 [==============================] - 0s 535us/step - loss: 0.5529 - accuracy: 0.7296
Epoch 34/50
804/804 [==============================] - 0s 538us/step - loss: 0.5529 - accuracy: 0.7292
Epoch 35/50
804/804 [==============================] - 0s 539us/step - loss: 0.5527 - accuracy: 0.7291
Epoch 36/50
804/804 [==============================] - 0s 519us/step - loss: 0.5525 - accuracy: 0.7290
Epoch 37/50
804/804 [==============================] - 0s 528us/step - loss: 0.5527 - accuracy: 0.7302
Epoch 38/50
804/804 [==============================] - 0s 539us/step - loss: 0.5524 - accuracy: 0.7284
Epoch 39/50
804/804 [==============================] - 0s 519us/step - loss: 0.5527 - accuracy: 0.7294
Epoch 40/50
804/804 [==============================] - 0s 538us/step - loss: 0.5526 - accuracy: 0.7298
Epoch 41/50
804/804 [==============================] - 0s 526us/step - loss: 0.5528 - accuracy: 0.7293
Epoch 42/50
804/804 [==============================] - 0s 530us/step - loss: 0.5524 - accuracy: 0.7289
Epoch 43/50
804/804 [==============================] - 0s 586us/step - loss: 0.5524 - accuracy: 0.7308
Epoch 44/50
804/804 [==============================] - 0s 551us/step - loss: 0.5525 - accuracy: 0.7297
Epoch 45/50
804/804 [==============================] - 0s 551us/step - loss: 0.5525 - accuracy: 0.7290
Epoch 46/50
804/804 [==============================] - 0s 539us/step - loss: 0.5525 - accuracy: 0.7296
Epoch 47/50
804/804 [==============================] - 0s 528us/step - loss: 0.5522 - accuracy: 0.7300
Epoch 48/50
804/804 [==============================] - 0s 546us/step - loss: 0.5524 - accuracy: 0.7286
Epoch 49/50
804/804 [==============================] - 0s 546us/step - loss: 0.5526 - accuracy: 0.7293
Epoch 50/50
804/804 [==============================] - 0s 542us/step - loss: 0.5523 - accuracy: 0.7295
268/268 - 0s - loss: 0.5543 - accuracy: 0.7324 - 159ms/epoch - 592us/step
Loss: 0.5542851686477661, Accuracy: 0.7323614954948425

In [122]:
# Export our model to HDF5 file
import h5py
f1 = h5py.File("data.hdf5", "w")